name: Run tModUnpacker

on:
  workflow_dispatch:

jobs:
  run-tmodunpacker:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up environment
      run: |
        . ./input.sh
      shell: bash

    - name: Create directories if they don't exist
      run: |
        mkdir -p tmodFilesExtracted/$TMODFILE/
      env:
        TMODFILE: ${{ env.TMODFILE }}

    - name: Run tModUnpacker
      run: |
        ./tModUnpacker.exe tmodFiles/$TMODFILE tmodFilesExtracted/$TMODFILE/
      env:
        TMODFILE: ${{ env.TMODFILE }}
        
    - name: Commit and push changes
      run: |
        git add files_extracted/$TMODFILE/
        git commit -m "Extracted $TMODFILE"
        git push
      env:
        TMODFILE: ${{ env.TMODFILE }}
