name: workshop-dl

on:
  workflow_dispatch:

jobs:
  setup-and-download-entry:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up and download entry
        run: |
          sudo add-apt-repository -y multiverse
          sudo dpkg --add-architecture i386
          echo steam steam/question select "I AGREE" | sudo debconf-set-selections
          echo steam steam/license note "" | sudo debconf-set-selections
          sudo apt update
          sudo apt install -y steamcmd

          GIT_ROOT=$(pwd)
          echo "pwd: $GIT_ROOT"
          sudo chmod +x $GIT_ROOT/input.sh
          source $GIT_ROOT/input.sh
          exec steamcmd +login anonymous +workshop_download_item $APP_ID $ENTRY_ID +quit
          mv /home/runner/Steam/steamapps/workshop/content/$APP_ID/$ENTRY_ID $GIT_ROOT/downloaded/
          tree -i $GIT_ROOT
        shell: bash

      - name: Push downloaded contents to repository
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Add downloaded workshop item $ENTRY_ID"
          git push
        shell: bash
